./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/poi-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/poi-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/poi-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/poi-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/poi-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/poi-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/poi-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/poi-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/poi-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/poi-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/poi-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/poi-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/poi-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/poi-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/poi-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/poi-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/poi-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/poi-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/poi-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/poi-50-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-100-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/r-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/r-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/r-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/r-150-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-50-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-100-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/c1-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/c1-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/c1-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/c1-150-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-50-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-50-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-50-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-50-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-50-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-50-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-100-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-100-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-100-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-100-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-100-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-100-5.oplib

./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.2T/rc1-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.3T/rc1-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.4T/rc1-150-5.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-150-1.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-150-2.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-150-3.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-150-4.oplib
./src/op-solver opt --op-exact 1 OPLib/instances/opmd/0.5T/rc1-150-5.oplib



